# Настройки для развертывания Worker в Cloudflare
name = "spicy-stats"
main = "worker.js"
compatibility_date = "2024-03-01"

# Привязка вашей базы данных D1
[[d1_databases]]
binding = "DB"                               # Обязательно "DB", так как это используется в worker.js
database_name = "spicy-stats-db"             # Замените на имя вашей D1 базы данных в Cloudflare
database_id = "1b38736f-6c89-43c2-a7f0-28c0287df169"   # Реальный ID вашей D1 базы данных
