name: Deploy Backend to Cloudflare Worker

on:
  push:
    branches:
      - main     # Name of your main branch (change to master if the main branch is master)
    paths:
      - 'cloudflare_pages/**' # Trigger deploy only when files in this folder change

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Cloudflare Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: 'cloudflare_pages'
